In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import imread
import pandas as pd
import seaborn as sns
from sklearn.datasets.samples_generator import make_blobs, make_circles, make_moons
from sklearn.cluster import KMeans, SpectralClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_samples, silhouette_score

In [92]:
df_profiles = pd.read_csv('../data/raw/profiles.csv')
df_profiles

pid   p0   p1   p2   p3   p4   p5   p6   p7   p8  ...  p56  p57  \
0      196356  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1      204083  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
2      170667  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
3      115511  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
4      129719  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
5      174347  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
6      143618  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
7      116999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
8      194535  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
9      125275  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
10     138709  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
11     145774  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
12     110116  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
13     127217  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
14     153142  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
15     115485  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
16     113666  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
17     122046  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
18     167717  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
19     141405  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
20     186565  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
21     165770  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
22     127706  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
23     113516  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
24     127912  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
25     135378  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
26     215572  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
27     104039  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
28     101221  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
29     133559  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
63060  177571  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63061  160099  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63062  187865  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63063  151880  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63064  204949  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63065  158320  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63066  148673  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63067  209025  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63068  192010  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63069  123444  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63070  180496  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63071  155958  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63072  185094  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63073  164127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63074  187839  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63075  179816  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63076  138212  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63077  100087  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63078  215762  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63079  161736  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63080 

In [51]:
# Standardize the data
X_std = StandardScaler().fit_transform(df_profiles)

# Run local implementation of kmeans
km = KMeans(n_clusters=4)
km.fit(X_std)
centroids = km.cluster_centers_
labels = km.labels_

In [55]:
labels

array([1, 3, 3, ..., 2, 3, 2], dtype=int32)

In [59]:
labels[0]

1

In [64]:
for each in range(len(df_profiles_kmeans4)):
    x = labels[each]
    y = labels[each]
    df_profiles_kmeans4.loc[df_profiles_kmeans4.index == each, 'cluster_id'] = str(y)

In [65]:
df_profiles_kmeans4

pid   p0   p1   p2   p3   p4   p5   p6   p7   p8  ...  p57  p58  \
0      196356  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1      204083  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
2      170667  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
3      115511  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
4      129719  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
5      174347  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
6      143618  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
7      116999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
8      194535  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
9      125275  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
10     138709  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
11     145774  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
12     110116  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
13     127217  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
14     153142  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
15     115485  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
16     113666  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
17     122046  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
18     167717  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
19     141405  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
20     186565  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
21     165770  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
22     127706  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
23     113516  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
24     127912  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
25     135378  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
26     215572  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
27     104039  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
28     101221  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
29     133559  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
63060  177571  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63061  160099  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63062  187865  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63063  151880  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63064  204949  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
63065  158320  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63066  148673  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63067  209025  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63068  192010  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63069  123444  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63070  180496  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63071  155958  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63072  185094  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63073  164127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63074  187839  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63075  179816  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
63076  138212  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63077  100087  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63078  215762  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
63079  161736  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63080 

In [56]:
test = []

for each in labels:
    if each not in test:
        test.append(each)
test

[1, 3, 2, 0]

In [5]:
centroids

array([[ 1.23444034e-02, -4.06465394e-01, -2.35599442e-02,
         1.64094390e-01,  1.48218926e-01,  7.02578078e-02,
         3.73521742e-02,  8.25478627e-03, -2.54193304e-01,
         2.54919632e-01,  4.01614894e-01, -2.00703622e-01,
        -3.00138919e-02, -1.05339888e-02, -4.20326460e-02,
        -4.51161138e-02,  3.15384550e-02,  5.71431113e-02,
         8.51517447e-02,  7.65293201e-02,  4.68078789e-02,
         3.61675544e-02,  9.70224209e-02,  5.48993917e-02,
        -1.64470657e-03,  9.75378940e-04, -3.70997020e-02,
        -1.20513473e-01, -6.07499980e-02,  2.92115063e-02,
         1.76581610e-01, -1.51153562e+00,  1.52036974e+00,
        -1.58295552e-02, -3.54890653e-01,  2.86237638e-01,
         4.21187437e-02,  7.99881936e-02, -1.17007404e-01,
         1.03606163e-03,  1.08357476e-04, -1.59123879e-02,
        -9.40591250e-03,  2.36666817e-03, -2.14859096e-02,
         1.50998079e-02,  3.00095778e-02,  3.02395088e-02,
        -1.50265106e-02, -2.41174084e-02, -3.52999609e-0

In [6]:
np.save('../data/task2/kmeans4.npy', centroids)

In [88]:
np.save('../data/task2/kmeeans_cluster4.npy', labels)

In [49]:
kmeans4 = pd.DataFrame()

for each in range(len(centroids)):
    cluster_each = 'Cluster_'+str(each+1)
    
    kmeans4[cluster_each] = centroids[each]
kmeans4

Cluster_1  Cluster_2  Cluster_3  Cluster_4
0    0.012344   0.008096  -0.013626  -0.007983
1   -0.406465  -0.366145   1.502531  -0.433980
2   -0.023560  -0.023560   0.087473  -0.023560
3    0.164094   0.068812  -0.576234   0.216254
4    0.148219   0.102602  -0.528739   0.168945
5    0.070258   0.165938  -0.318999   0.036304
6    0.037352   0.133305  -0.141056  -0.037927
7    0.008255   0.052334  -0.059264  -0.006040
8   -0.254193   0.087311  -0.125155   0.259497
9    0.254920  -0.087028   0.124663  -0.260039
10   0.401615   0.103038  -0.781746   0.118474
11  -0.200704  -0.255516   0.830019  -0.219240
12  -0.030014  -0.029712   0.113619  -0.031866
13  -0.010534  -0.010534   0.039110  -0.010534
14  -0.042033  -0.043426   0.158316  -0.042578
15  -0.045116   0.002320  -0.034144   0.065429
16   0.031538   0.010832  -0.096579   0.033040
17   0.057143   0.000624  -0.140061   0.049375
18   0.085152  -0.003292  -0.186700   0.060742
19   0.076529   0.024036  -0.209434   0.063610
20   0.046808   0.001307  -0.157756   0.071520
21   0.036168  -0.005297  -0.014319  -0.018965
22   0.097022   0.052095  -0.288157   0.079974
23   0.054899  -0.003758  -0.159907   0.069615
24  -0.001645  -0.003266   0.008656  -0.002222
25   0.000975  -0.009438  -0.021057   0.022186
26  -0.037100  -0.038628   0.141482  -0.038628
27  -0.120513  -0.172185   0.184687   0.114630
28  -0.060750  -0.157755   0.141301   0.079220
29   0.029212   0.122970  -0.251617   0.059461
..        ...        ...        ...        ...
37   0.079988   0.165508  -0.148667  -0.097979
38  -0.117007  -0.204763   0.158579   0.156752
39   0.001036  -0.001903   0.001815  -0.000777
40   0.000108  -0.024633   0.021328   0.003955
41  -0.015912   0.017727  -0.006999   0.005785
42  -0.009406  -0.005255   0.021333  -0.002722
43   0.002367   0.011452  -0.046090   0.022567
44  -0.021486   0.000953   0.014744   0.008430
45   0.015100   0.018003  -0.023208  -0.011446
46   0.030010   0.002881  -0.013390  -0.020464
47   0.030240   0.023622  -0.034378  -0.021860
48  -0.015027  -0.016090  -0.024561   0.045050
49  -0.024117  -0.004017   0.038802  -0.002856
50  -0.035300  -0.012119   0.039631   0.013479
51   0.015127  -0.011353  -0.006965   0.000123
52   0.075027  -0.019721  -0.015876  -0.042520
53  -0.007400   0.027262   0.019872  -0.029623
54  -0.046867  -0.026416   0.081096   0.005195
55   0.011599   0.037670  -0.081990   0.019359
56  -0.031893  -0.021598   0.041616   0.016445
57   0.076607  -0.017411  -0.056072  -0.016224
58   0.025614   0.052601  -0.052049  -0.027781
59   0.002942   0.011793   0.008000  -0.018111
60  -0.041829  -0.035476   0.078501   0.009678
61   0.198498  -0.029241  -0.191827  -0.020480
62  -0.027912   0.025624   0.042504  -0.025837
63  -0.101253  -0.009603   0.063497   0.055450
64   0.001955   0.038130  -0.010410  -0.024764
65  -0.044874   0.025044  -0.031294   0.044860
66   0.018045  -0.000486   0.016732  -0.028791

[67 rows x 4 columns]

In [93]:
# Standardize the data
X_std = StandardScaler().fit_transform(df_profiles)

# Run local implementation of kmeans
km = KMeans(n_clusters=8)
km.fit(X_std)
centroids8 = km.cluster_centers_
labels8 = km.labels_

In [94]:
labels8

array([2, 2, 7, ..., 6, 4, 6], dtype=int32)

In [8]:
np.save('../data/task2/kmeans8.npy', centroids8)

In [99]:
np.save('../data/task2/kmeeans_cluster8.npy', labels8)

In [95]:
# Standardize the data
X_std = StandardScaler().fit_transform(df_profiles)

# Run local implementation of kmeans
km = KMeans(n_clusters=16)
km.fit(X_std)
centroids16 = km.cluster_centers_
labels16 = km.labels_

In [96]:
labels16

array([ 1, 10,  4, ...,  8,  5,  4], dtype=int32)

In [10]:
np.save('../data/task2/kmeans16.npy', centroids16)

In [100]:
np.save('../data/task2/kmeeans_cluster16.npy', labels16)

In [97]:
# Standardize the data
X_std = StandardScaler().fit_transform(df_profiles)

# Run local implementation of kmeans
km = KMeans(n_clusters=36)
km.fit(X_std)
centroids36 = km.cluster_centers_
labels36 = km.labels_

In [98]:
labels36

array([28,  6, 29, ...,  4,  5, 29], dtype=int32)

In [12]:
np.save('../data/task2/kmeans36.npy', centroids36)

In [101]:
np.save('../data/task2/kmeeans_cluster36.npy', labels36)

In [6]:
df_silhouette = pd.DataFrame(columns = ['cluster_type', 'n_cluster', 'avg_score'])
df_silhouette

Empty DataFrame
Columns: [cluster_type, n_cluster, avg_score]
Index: []

In [8]:
rows = df_profiles.index

In [18]:
excerpt_rows = rows[130:500]
excerpt_rows

RangeIndex(start=130, stop=500, step=1)

In [19]:
count = []

for each in excerpt_rows:
    each = int(each)
    
    if each  not in count:
        count.append(each)

In [20]:
'''
Silhouette Analysis used to determine the degree of separation between clusters. For each sample:
1) Compute the average distance from all data points in the same cluster (ai).
2) Compute the average distance from all data points in the closest cluster (bi).
3) Compute the coefficient: Values in the interval [-1, 1]
    * 0 –> the sample is very close to the neighboring clusters.
    * 1 –> the sample is far away from the neighboring clusters.
    * -1 –> the sample is assigned to the wrong clusters.
'''

for i, k in enumerate(count):
    
    # Run the Kmeans algorithm
    km = KMeans(n_clusters=k)
    labels = km.fit_predict(X_std)
    centroids = km.cluster_centers_

    # Get silhouette samples
    silhouette_vals = silhouette_samples(X_std, labels)

    # Silhouette
    for i, cluster in enumerate(np.unique(labels)):
        cluster_silhouette_vals = silhouette_vals[labels == cluster]
        cluster_silhouette_vals.sort()
        
    # Get the average silhouette score
    avg_score = np.mean(silhouette_vals)
    
    if k % 50 == 0:
        print(f'Current n_cluster {k} with avg_score = {avg_score}')
    
    df_silhouette.loc[i, 'cluster_type'] = 'KMeans'
    df_silhouette.loc[i, 'n_cluster'] = k
    df_silhouette.loc[i, 'avg_score'] = avg_score


KeyboardInterrupt: 

In [21]:
df_silhouette

cluster_type n_cluster  avg_score
129       KMeans       130  0.0802393
130       KMeans       131  0.0814365
131       KMeans       132  0.0889016
132       KMeans       133  0.0775118
133       KMeans       134  0.0807942
134       KMeans       135  0.0823189
135       KMeans       136  0.0803586
136       KMeans       137  0.0834806
137       KMeans       138  0.0819528
138       KMeans       139  0.0832413
139       KMeans       140  0.0801977
140       KMeans       141  0.0829999
141       KMeans       142  0.0853001
142       KMeans       143  0.0829152
143       KMeans       144  0.0839768
144       KMeans       145  0.0793882
145       KMeans       146  0.0822018
146       KMeans       147   0.078435

In [22]:
for i, k in enumerate([148, 149, 150]):
    
    # Run the Kmeans algorithm
    km = KMeans(n_clusters=k)
    labels = km.fit_predict(X_std)
    centroids = km.cluster_centers_

    # Get silhouette samples
    silhouette_vals = silhouette_samples(X_std, labels)

    # Silhouette
    for i, cluster in enumerate(np.unique(labels)):
        cluster_silhouette_vals = silhouette_vals[labels == cluster]
        cluster_silhouette_vals.sort()
        
    # Get the average silhouette score
    avg_score = np.mean(silhouette_vals)
    
    if k % 50 == 0:
        print(f'Current n_cluster {k} with avg_score = {avg_score}')
    
    df_silhouette.loc[i, 'cluster_type'] = 'KMeans'
    df_silhouette.loc[i, 'n_cluster'] = k
    df_silhouette.loc[i, 'avg_score'] = avg_score


Current n_cluster 150 with avg_score = 0.08154976785749042


In [23]:
df_silhouette

cluster_type n_cluster  avg_score
129       KMeans       130  0.0802393
130       KMeans       131  0.0814365
131       KMeans       132  0.0889016
132       KMeans       133  0.0775118
133       KMeans       134  0.0807942
134       KMeans       135  0.0823189
135       KMeans       136  0.0803586
136       KMeans       137  0.0834806
137       KMeans       138  0.0819528
138       KMeans       139  0.0832413
139       KMeans       140  0.0801977
140       KMeans       141  0.0829999
141       KMeans       142  0.0853001
142       KMeans       143  0.0829152
143       KMeans       144  0.0839768
144       KMeans       145  0.0793882
145       KMeans       146  0.0822018
146       KMeans       147   0.078435
147       KMeans       148  0.0792374
148       KMeans       149  0.0788277
149       KMeans       150  0.0815498

In [ ]:
df_silhouette.to_csv("../data/task2/")

In [14]:
df_scores = pd.read_csv('../data/task2/silhouette.csv')
df_scores

Unnamed: 0 cluster_type  n_cluster  avg_score
0             1       KMeans          2   0.042845
1             2       KMeans          3   0.035767
2             3       KMeans          4   0.040143
3             4       KMeans          5   0.039844
4             5       KMeans          6   0.039268
5             6       KMeans          7   0.024363
6             7       KMeans          8   0.061844
7             8       KMeans          9   0.041767
8             9       KMeans         10   0.055749
9            10       KMeans         11   0.049665
10           11       KMeans         12   0.072669
11           12       KMeans         13   0.067810
12           13       KMeans         14   0.092984
13           14       KMeans         15   0.094355
14           15       KMeans         16   0.114913
15           16       KMeans         17   0.124213
16           17       KMeans         18   0.122046
17           18       KMeans         19   0.126200
18           19       KMeans         20   0.119467
19           20       KMeans         21   0.129029
20           21       KMeans         22   0.142649
21           22       KMeans         23   0.151985
22           23       KMeans         24   0.125867
23           24       KMeans         25   0.149868
24           25       KMeans         26   0.154205
25           26       KMeans         27   0.167536
26           27       KMeans         28   0.149918
27           28       KMeans         29   0.151388
28           29       KMeans         30   0.171072
29           30       KMeans         31   0.160105
..          ...          ...        ...        ...
105         106       KMeans        107   0.083238
106         107       KMeans        108   0.084045
107         108       KMeans        109   0.084367
108         109       KMeans        110   0.084828
109         110       KMeans        111   0.081088
110         111       KMeans        112   0.087005
111         112       KMeans        113   0.087376
112         113       KMeans        114   0.086033
113         114       KMeans        115   0.087790
114         115       KMeans        116   0.085717
115         116       KMeans        117   0.085594
116         117       KMeans        118   0.084344
117         118       KMeans        119   0.077245
118         119       KMeans        120   0.080939
119         120       KMeans        121   0.084820
120         121       KMeans        122   0.087592
121         122       KMeans        123   0.080223
122         123       KMeans        124   0.084057
123         124       KMeans        125   0.087156
124         125       KMeans        126   0.085443
125         126       KMeans        127   0.078847
126         127       KMeans        128   0.081747
127         128       KMeans        129   0.077801
128         129       KMeans        130   0.081523
129         499       KMeans        500   0.097487
130         524       KMeans        525   0.098938
131         549       KMeans        550   0.098012
132         574       KMeans        575   0.096033
133         599       KMeans        600   0.095256
134         624       KMeans        625   0.098169

[135 rows x 4 columns]

In [8]:
df_scores[df_scores.avg_score == df_scores['avg_score'].max()]

Unnamed: 0 cluster_type  n_cluster  avg_score
34          35       KMeans         36   0.174719

In [18]:
df_a = df_scores.loc[[2,  6, 14, 34], :]
df_a

Unnamed: 0 cluster_type  n_cluster  avg_score
2            3       KMeans          4   0.040143
6            7       KMeans          8   0.061844
14          15       KMeans         16   0.114913
34          35       KMeans         36   0.174719

In [21]:
df_a.to_csv("../data/task2/silhouette_filterred.csv")

In [87]:
df_kmeans = pd.read_csv('../data/raw/profiles.csv')

cluster = [4, 8, 16, 36]

for each in cluster:
    df_kmeans[f'cluster{each}_id']=np.nan
df_kmeans

pid   p0   p1   p2   p3   p4   p5   p6   p7   p8  ...  p60  p61  \
0      196356  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1      204083  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
2      170667  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
3      115511  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
4      129719  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
5      174347  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
6      143618  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
7      116999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
8      194535  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
9      125275  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
10     138709  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
11     145774  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
12     110116  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
13     127217  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
14     153142  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
15     115485  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
16     113666  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
17     122046  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
18     167717  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
19     141405  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
20     186565  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
21     165770  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
22     127706  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
23     113516  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
24     127912  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
25     135378  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
26     215572  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
27     104039  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
28     101221  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
29     133559  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
63060  177571  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63061  160099  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63062  187865  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63063  151880  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
63064  204949  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63065  158320  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63066  148673  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63067  209025  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
63068  192010  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
63069  123444  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63070  180496  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63071  155958  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63072  185094  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63073  164127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63074  187839  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63075  179816  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63076  138212  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63077  100087  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63078  215762  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63079  161736  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63080 

In [107]:
for each in range(len(df_kmeans)):
    x = labels36[each]
    df_kmeans.loc[df_kmeans.index == each, 'cluster36_id'] = str(x)
df_kmeans

pid   p0   p1   p2   p3   p4   p5   p6   p7   p8  ...  p60  p61  \
0      196356  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1      204083  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
2      170667  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
3      115511  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
4      129719  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
5      174347  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
6      143618  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
7      116999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
8      194535  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
9      125275  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
10     138709  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
11     145774  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
12     110116  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
13     127217  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
14     153142  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
15     115485  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
16     113666  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
17     122046  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
18     167717  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
19     141405  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
20     186565  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
21     165770  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
22     127706  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
23     113516  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
24     127912  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
25     135378  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
26     215572  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
27     104039  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
28     101221  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
29     133559  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
63060  177571  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63061  160099  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63062  187865  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63063  151880  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
63064  204949  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63065  158320  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63066  148673  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63067  209025  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
63068  192010  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0   
63069  123444  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63070  180496  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63071  155958  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63072  185094  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63073  164127  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63074  187839  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63075  179816  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63076  138212  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63077  100087  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63078  215762  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0   
63079  161736  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
63080 

In [109]:
df_kmeans.to_csv("../data/task2/kmeans/df_kmeans.csv")

In [110]:
n_cluster = df_kmeans.cluster4_id.unique()
n_cluster

array(['1', '3', '2', '0'], dtype=object)

In [111]:
for each in n_cluster:
    cluster_each = []
    print(f'Cluster {each}: ', cluster_each)

Cluster 1:  []
Cluster 3:  []
Cluster 2:  []
Cluster 0:  []


In [136]:
df1 = df_kmeans.loc[df_kmeans['cluster4_id'] == '1']
df1

pid   p0   p1   p2   p3   p4   p5   p6   p7   p8  ...  p60  p61  \
0      196356  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
3      115511  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
7      116999  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
10     138709  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
11     145774  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
12     110116  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
13     127217  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
15     115485  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
23     113516  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
25     135378  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
28     101221  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
29     133559  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
30     171068  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
34     160187  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
35     169390  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
41     168142  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
43     207855  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
44     210697  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
45     166867  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
47     165775  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
49     171357  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0   
51     130311  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
52     144813  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
54     182716  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  0.0   
55     183949  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
56     200957  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
58     213149  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
60     210492  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
61     157438  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
67     127105  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
63015  208924  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63018  117593  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63020  104873  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63023  109209  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63028  209479  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63032  179682  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63033  204668  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63034  153511  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63035  145747  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63037  101951  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63038  207411  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63040  109432  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63044  114569  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  0.0   
63053  159654  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63054  125592  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63055  213569  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0   
63056  174847  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63058  192708  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63061  160099  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63062  187865  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
63063 

In [137]:
df1.pid[0]

196356

In [151]:
len(df1)

23492

In [160]:
a = np.array(df_kmeans.pid.loc[df_kmeans['cluster4_id'] == '1'])
len(a)

23492

In [162]:
cluster4 = []

for each in n_cluster:
    x = str(each)
    a = np.array(df_kmeans.pid.loc[df_kmeans['cluster4_id'] == x])
    cluster4.append(a)
cluster4

[array([196356, 115511, 116999, ..., 146014, 216637, 129022]),
 array([204083, 170667, 174347, ..., 105588, 195899, 124392]),
 array([129719, 153142, 106121, ..., 130062, 103194, 120234]),
 array([166862, 131329, 100953, 139467, 131849, 171295, 167773, 114731,
        158429, 181877, 168568, 205672, 160410, 100677, 140290, 119977,
        201017, 150898, 187731, 132805, 181595, 190976, 155143, 124458,
        172098, 179756, 178107, 159560, 124896, 134941, 122563, 108599,
        150008, 211228, 159804, 201373, 150429, 174559, 193784, 153557,
        136745, 150422, 149363, 157391, 178510, 159455, 114114, 129271,
        196024, 178998, 148868, 140886, 100812, 190475, 147721, 117446,
        216585, 126034, 148787, 169322, 206932, 181435, 208143, 103804,
        105230, 171327, 128379, 102357, 158910, 132165, 155190, 164853,
        167746, 215383, 212769, 202642, 121909, 123571, 186546, 153865,
        174440, 103343, 209157, 143108, 119790, 137038, 183701, 102373,
        177643, 108

In [163]:
len(cluster4[0])

23492

In [164]:
np.save('../data/task2/cluster4.npy', cluster4)

In [165]:
n_cluster = df_kmeans.cluster8_id.unique()
cluster8 = []

for each in n_cluster:
    x = str(each)
    a = np.array(df_kmeans.pid.loc[df_kmeans['cluster8_id'] == x])
    cluster8.append(a)
len(cluster8)

8

In [166]:
np.save('../data/task2/cluster8.npy', cluster8)

In [167]:
n_cluster = df_kmeans.cluster16_id.unique()
cluster16 = []

for each in n_cluster:
    x = str(each)
    a = np.array(df_kmeans.pid.loc[df_kmeans['cluster16_id'] == x])
    cluster16.append(a)
len(cluster16)

16

In [168]:
np.save('../data/task2/cluster16.npy', cluster16)

In [169]:
n_cluster = df_kmeans.cluster36_id.unique()
cluster36 = []

for each in n_cluster:
    x = str(each)
    a = np.array(df_kmeans.pid.loc[df_kmeans['cluster36_id'] == x])
    cluster36.append(a)
len(cluster36)

36

In [170]:
np.save('../data/task2/cluster36.npy', cluster36)